/* linux/arch/arm/mach-exynos/stuttgart_gpio_evt.h
 *
 * Copyright (c) 2011 Samsung Electronics Co., Ltd.
 *		http://www.samsung.com
 *
 *  jeff@sscr, define the init gpio and sleep gpio setting for stuttgart EVT platform
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

/* stuttgart EVT board specific defines*/


#ifndef __STUTTGART_GPIO__
#define __STUTTGART_GPIO__

#include <linux/gpio.h>
#include <plat/exynos4.h>
#include <plat/gpio-cfg.h>
#include <plat/gpio-core.h>

#define S3C_GPIO_SETPIN_ZERO	0
#define S3C_GPIO_SETPIN_ONE	1
#define S3C_GPIO_SETPIN_NONE	2

struct gpio_init_data {
	uint num;
	uint cfg;
	uint val;
	uint pud;
	uint drv;
};

static struct gpio_init_data stuttgart_init_gpio_table[] = 
{
	/* GPB[0-3], floating*/
	{
		.num= EXYNOS4_GPB(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num= EXYNOS4_GPB(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num= EXYNOS4_GPB(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num= EXYNOS4_GPB(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, 

	/* TODO, init GPIO table */
};


//stuttgart sleep table

static unsigned int stuttgart_sleep_gpio_table[][3] = {
	/* GPA */
	/* BT UART */
	{ EXYNOS4_GPA0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA0(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA0(3), S5P_GPIO_PD_OUTPUT1, S3C_GPIO_PULL_NONE},

	/* Modem UART, TODO: check modem , ?????? jeff */
	{ EXYNOS4_GPA0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA0(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA0(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA0(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},

	/* GPS UART */
	{ EXYNOS4_GPA1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPA1(1), S5P_GPIO_PD_OUTPUT1,S3C_GPIO_PULL_NONE}, //S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN
	{ EXYNOS4_GPA1(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA1(3), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_DOWN}, //S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN

	/* Debug UART */
	{ EXYNOS4_GPA1(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPA1(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},

	/* GPB */
	/* I2C4, SENSOR */
	{ EXYNOS4_GPB(0),  S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(1),  S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	/* I2C5, CODEC */
	{ EXYNOS4_GPB(2),  S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(3),  S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	/* NC */
	{ EXYNOS4_GPB(4),  S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPB(5),  S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPB(6),  S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPB(7),  S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},

	/* GPC */
	/* PCM1 */
	{ EXYNOS4_GPC0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN}, 
	{ EXYNOS4_GPC0(1), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* SUBCCM_PD : need check*/
	{ EXYNOS4_GPC0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPC0(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPC0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},

	/* CP pins: TODO  */
//	{ EXYNOS4_GPC1(0), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* ? */
//	{ EXYNOS4_GPC1(1), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* ? */
	{ EXYNOS4_GPC1(2), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* ? */

	/* I2C6, CAM */
	{ EXYNOS4_GPC1(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPC1(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},	

	/* GPD */
	{ EXYNOS4_GPD0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},  /* NC */
	/* LCD PWM*/
	{ EXYNOS4_GPD0(1), S5P_GPIO_PD_OUTPUT0, S3C_GPIO_PULL_NONE},
	/* I2C7 M/P_SENSOR */
	{ EXYNOS4_GPD0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPD0(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	
	/* I2C0, PMIC*/
	{ EXYNOS4_GPD1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPD1(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	/* I2C1 TP,BL */
	{ EXYNOS4_GPD1(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPD1(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},

	/* GPF */
	{ EXYNOS4_GPF0(0), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* LCD_RST */ 
	{ EXYNOS4_GPF0(1), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* TP_RST */
	{ EXYNOS4_GPF0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPF0(3), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* CAM8M_PWR */
	{ EXYNOS4_GPF0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NORMAL_STAT */
//	{ EXYNOS4_GPF0(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* CP_REQ_SUSPEND_IPC, CP ?*/
	{ EXYNOS4_GPF0(6), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* USB_SW */
	{ EXYNOS4_GPF0(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */

	{ EXYNOS4_GPF1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPF1(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPF1(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPF1(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPF1(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* EINT14_CAM8M  ?*/
	{ EXYNOS4_GPF1(5), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* RST_CAM8M  ?*/
	{ EXYNOS4_GPF1(6), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* PWN_CAM8M  ?*/
	{ EXYNOS4_GPF1(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */

	{ EXYNOS4_GPF2(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPF2(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* IPC_OPTIONAL_1 : CP?*/
//	{ EXYNOS4_GPF2(2), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* MODEM_RST : CP?*/
//	{ EXYNOS4_GPF2(3), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* MODEM_PWRDWN : CP?*/

	/* setup for BT*/
	{ EXYNOS4_GPF2(4), S5P_GPIO_PD_PREV_STATE, S3C_GPIO_PULL_NONE},   /* AP_WAKE_BT */
	{ EXYNOS4_GPF2(5), S5P_GPIO_PD_PREV_STATE, S3C_GPIO_PULL_NONE},   /* BT, PWR_BT */
	{ EXYNOS4_GPF2(6), S5P_GPIO_PD_PREV_STATE, S3C_GPIO_PULL_NONE},   /* BT, RST_BT */
	{ EXYNOS4_GPF2(7), S5P_GPIO_PD_INPUT, S3C_GPIO_PULL_DOWN},        /* SW_DBG, ???jeff, need check: S5P_GPIO_PD_OUTPUT0, S3C_GPIO_PULL_NONE */

//	{ EXYNOS4_GPF3(0), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* MODEM_PG  */
//	{ EXYNOS4_GPF3(1), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* MODEM_PWRON  */
	{ EXYNOS4_GPF3(2), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* RST_CAM2M  */
	{ EXYNOS4_GPF3(3), S5P_GPIO_PD_PREV_STATE,	S3C_GPIO_PULL_NONE},   /* PWR_WIFI  */
	{ EXYNOS4_GPF3(4), S5P_GPIO_PD_PREV_STATE,	S3C_GPIO_PULL_NONE},   /* GPC_ON */
	{ EXYNOS4_GPF3(5), S5P_GPIO_PD_PREV_STATE,	S3C_GPIO_PULL_NONE},   /* GPS_RST*/

	/* GPJ */
	{ EXYNOS4212_GPJ0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* SUBCAM */ 
	{ EXYNOS4212_GPJ0(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ0(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ0(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ0(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ0(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4212_GPJ1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */ 
	{ EXYNOS4212_GPJ1(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ1(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ1(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPJ1(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */

	/* GPIO PART2 */
	/* GPK */
	{ EXYNOS4_GPK0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* MoviNand */ 
	{ EXYNOS4_GPK0(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* MN,reset, check? */
	{ EXYNOS4_GPK0(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* DATA, PULL_NONE? */
	{ EXYNOS4_GPK0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK0(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK0(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */

	{ EXYNOS4_GPK1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4_GPK1(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPK1(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPK1(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* MoviNand DATA*/
	{ EXYNOS4_GPK1(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK1(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK1(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */

	{ EXYNOS4_GPK2(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* SD CARD */ 
	{ EXYNOS4_GPK2(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* DATA, PULL_NONE, OUTPUT1?  */
	{ EXYNOS4_GPK2(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPK2(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK2(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK2(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK2(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */

	{ EXYNOS4_GPK3(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* WLAN */ 
	{ EXYNOS4_GPK3(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK3(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPK3(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK3(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK3(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */
	{ EXYNOS4_GPK3(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* */

	/* GPL */
	/* DVS PINs are not used now, set none */
	{ EXYNOS4_GPL0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* SELB2_PMIC */ 
	{ EXYNOS4_GPL0(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* SELB3_PMIC */
	{ EXYNOS4_GPL0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* SELB4_PMIC */
	{ EXYNOS4_GPL0(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* DVS1 */
	{ EXYNOS4_GPL0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* DVS2 */
	{ EXYNOS4_GPL0(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC? not in sche*/
	{ EXYNOS4_GPL0(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* DVS3 */

	{ EXYNOS4_GPL1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPL1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */

	{ EXYNOS4_GPL2(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* RESERVE_ID0 */ 
	{ EXYNOS4_GPL2(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* RESERVE_ID1 */
	{ EXYNOS4_GPL2(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPL2(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPL2(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPL2(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPL2(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPL2(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */

	/* GPY */
	/* GPY Group PINs are all NC on stuttgart, so default, Input Pull_down is ok*/
	{ EXYNOS4_GPY0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC  */ 
	{ EXYNOS4_GPY0(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /*  */
	{ EXYNOS4_GPY0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /*  */
	{ EXYNOS4_GPY0(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /*  */
	{ EXYNOS4_GPY0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY0(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	
	{ EXYNOS4_GPY1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC  */ 
	{ EXYNOS4_GPY1(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY1(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY1(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4_GPY2(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4_GPY2(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY2(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /*  */
	{ EXYNOS4_GPY2(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY2(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY2(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	
	{ EXYNOS4_GPY3(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4_GPY3(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY3(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY3(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY3(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY3(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY3(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY3(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	
	{ EXYNOS4_GPY4(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4_GPY4(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY4(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY4(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY4(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY4(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY4(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY4(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	
	{ EXYNOS4_GPY5(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4_GPY5(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY5(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY5(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY5(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY5(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY5(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY5(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4_GPY6(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4_GPY6(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY6(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /*  */
	{ EXYNOS4_GPY6(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY6(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY6(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY6(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4_GPY6(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	
	/* GPM */
	/* GPM Group PINs are all NC on stuttgart, except following 6 pins */
	{ EXYNOS4212_GPM0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4212_GPM0(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /*  */
	{ EXYNOS4212_GPM0(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM0(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM0(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM0(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4212_GPM1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4212_GPM1(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM1(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /*  */
	{ EXYNOS4212_GPM1(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM1(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4212_GPM2(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4212_GPM2(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM2(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /*  */
	{ EXYNOS4212_GPM2(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM2(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM2(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM2(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPM2(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4212_GPM3(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */ 
	{ EXYNOS4212_GPM3(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4212_GPM3(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4212_GPM3(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4212_GPM3(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4212_GPM3(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4212_GPM3(6), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* ISP_FLASH_EN */
	{ EXYNOS4212_GPM3(7), S5P_GPIO_PD_OUTPUT0,S3C_GPIO_PULL_NONE},   /* ISP_TORCH_E */

	{ EXYNOS4212_GPM4(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* ispI2C0 */ 
	{ EXYNOS4212_GPM4(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* ispI2C0*/
	{ EXYNOS4212_GPM4(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* ispI2C1 */
	{ EXYNOS4212_GPM4(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_NONE},   /* ispI2C1*/
	{ EXYNOS4212_GPM4(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4212_GPM4(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC*/
	{ EXYNOS4212_GPM4(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4212_GPM4(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* NC*/

	/* PART3 */
	/* GPZ */
	{ EXYNOS4_GPZ(0), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* I2S0 SCLK, need check?*/ 
	{ EXYNOS4_GPZ(1), S5P_GPIO_PD_PREV_STATE,S3C_GPIO_PULL_NONE},    /* I2C_PU_GPZ1, should be low in sleep */
	{ EXYNOS4_GPZ(2), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* I2S0 LRCLK */
	{ EXYNOS4_GPZ(3), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_DOWN},   /* I2S0 SDI*/
	{ EXYNOS4_GPZ(4), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},   /* I2S0 SDO */
	{ EXYNOS4_GPZ(5), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_DOWN},   /* NC */
	{ EXYNOS4_GPZ(6), S5P_GPIO_PD_OUTPUT0,	S3C_GPIO_PULL_NONE},    /* Motor_en */

	/* PART4 */
	/* GPV, C2C NC on Stuttgart */
	{ EXYNOS4212_GPV0(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* nc */ 
	{ EXYNOS4212_GPV0(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV0(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV0(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV0(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV0(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV0(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV0(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4212_GPV1(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* nc */ 
	{ EXYNOS4212_GPV1(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV1(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV1(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV1(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV1(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV1(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV1(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4212_GPV2(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* nc */ 
	{ EXYNOS4212_GPV2(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV2(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV2(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV2(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV2(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV2(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV2(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4212_GPV3(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* nc */ 
	{ EXYNOS4212_GPV3(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV3(2), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV3(3), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV3(4), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV3(5), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV3(6), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */
	{ EXYNOS4212_GPV3(7), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	{ EXYNOS4212_GPV4(0), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* nc */ 
	{ EXYNOS4212_GPV4(1), S5P_GPIO_PD_INPUT,	S3C_GPIO_PULL_DOWN},   /* */

	/*jeff, setup for modmem*/
	{ EXYNOS4_GPF2(2), S5P_GPIO_PD_PREV_STATE, S3C_GPIO_PULL_NONE},   /* GPIO_CP_RST */
	{ EXYNOS4_GPF2(3), S5P_GPIO_PD_PREV_STATE, S3C_GPIO_PULL_NONE},   /* GPIO_CP_PMU_RST */
	{ EXYNOS4_GPF3(1), S5P_GPIO_PD_PREV_STATE, S3C_GPIO_PULL_NONE},   /* GPIO_PHONE_ON */

	{ EXYNOS4_GPC1(0), S5P_GPIO_PD_INPUT, S3C_GPIO_PULL_DOWN},        /* GPIO_IPC_SLAVE_WAKEUP */
	{ EXYNOS4_GPF0(5), S5P_GPIO_PD_INPUT, S3C_GPIO_PULL_NONE},        /* GPIO_SUSPEND_REQUEST */
	{ EXYNOS4_GPC1(1), S5P_GPIO_PD_INPUT, S3C_GPIO_PULL_NONE},        /* GPIO_ACTIVE_STATE */
	{ EXYNOS4_GPF3(0), S5P_GPIO_PD_PREV_STATE, S3C_GPIO_PULL_UP},     /* GPIO_CP_ABNORMAL_RESET_INT */
};

#endif
