snd-soc-mc_yamaha-objs := mc_asoc.o mc_asoc_dbg.o mc_asoc_parser.o \
	mcdevif.o mcdevprof.o mcdriver.o mcmachdep.o mcpacking.o mcresctrl.o mcservice.o mcdebuglog.o mccdspdrv.o

obj-$(CONFIG_SND_SOC_MC_YAMAHA) += snd-soc-mc_yamaha.o
