#
# Makefile for the linux kernel.
#

# Object file lists.

obj-$(CONFIG_SMM6260_MODEM) += smm6260_modem.o smm6260_acm.o smm6260_smd.o
obj-$(CONFIG_SMM6260_MODEM_TTY) += smm6260_tty.o
obj-$(CONFIG_SMM6260_MODEM_NET) += smm6260_net.o
